# Generated by Django 2.0.1 on 2018-01-28 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='MX', max_length=3, null=True, verbose_name='Pais')),
                ('region', models.CharField(max_length=100, verbose_name='Estado o Region')),
                ('town', models.CharField(max_length=100, verbose_name='Municipio o delegacion')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Colonia')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Código Postal')),
                ('street', models.CharField(max_length=100, verbose_name='Calle')),
                ('street_number', models.CharField(max_length=10, verbose_name='Número exterior')),
                ('suite_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero interior')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefono')),
                ('addresses', models.ManyToManyField(blank=True, to='users.Address')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Proveedor')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('extra_data', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Users Social Auth',
                'verbose_name_plural': 'User Social Auth',
            },
        ),
    ]
